<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FoundryDocumentIntelligence.Application\FoundryDocumentIntelligence.Application.csproj" />
    <ProjectReference Include="..\FoundryDocumentIntelligence.Infrastructure\FoundryDocumentIntelligence.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
